import img1 from './images/1.jpg';
import img2 from './images/2.jpg';
import img3 from './images/3.jpg';
import img4 from './images/4.jpg';
import img5 from './images/5.jpg';
import img6 from './images/6.jpg';
import img7 from './images/7.jpg';
import img8 from './images/8.jpeg';
import img9 from './images/9.jpeg';

const ImageData = [
    {
        img:img1,
        title:'1',
        cols:'2'
    },
    {
        img:img2,
        title:'2',
        cols:'1'
    },
    {
        img:img3,
        title:'3',
        cols:'2'
    },
    {
        img:img4,
        title:'4',
        cols:'1'
    },
    {
        img:img5,
        title:'5',
        cols:'1'
    },
    {
        img:img6,
        title:'6',
        cols:'1'
    },
    {
        img:img7,
        title:'7',
        cols:'1'
    },
    {
        img:img8,
        title:'8',
        cols:'1'
    },
    {
        img:img9,
        title:'9',
        cols:'2'
    },
    {
        img:img1,
        title:'10',
        cols:'2'
    },
    {
        img:img2,
        title:'11',
        cols:'1'
    },
    {
        img:img3,
        title:'12',
        cols:'2'
    },
    {
        img:img4,
        title:'13',
        cols:'1'
    },
    {
        img:img5,
        title:'14',
        cols:'1'
    },
    {
        img:img6,
        title:'15',
        cols:'1'
    },
    {
        img:img7,
        title:'16',
        cols:'1'
    },
    {
        img:img8,
        title:'17',
        cols:'1'
    },
    {
        img:img9,
        title:'18',
        cols:'2'
    },
    {
        img:img1,
        title:'19',
        cols:'2'
    },
    {
        img:img2,
        title:'20',
        cols:'1'
    },
    {
        img:img3,
        title:'21',
        cols:'2'
    },
    {
        img:img4,
        title:'22',
        cols:'1'
    },
    {
        img:img5,
        title:'23',
        cols:'1'
    },
    {
        img:img6,
        title:'24',
        cols:'1'
    },
    {
        img:img7,
        title:'25',
        cols:'1'
    },
    {
        img:img8,
        title:'26',
        cols:'1'
    },
    {
        img:img9,
        title:'27',
        cols:'2'
    },
    {
        img:img1,
        title:'28',
        cols:'2'
    },
    {
        img:img2,
        title:'29',
        cols:'1'
    },
    {
        img:img3,
        title:'30',
        cols:'2'
    },
    {
        img:img4,
        title:'31',
        cols:'1'
    },
    {
        img:img5,
        title:'32',
        cols:'1'
    },
    {
        img:img6,
        title:'33',
        cols:'1'
    },
    {
        img:img7,
        title:'34',
        cols:'1'
    },
    {
        img:img8,
        title:'35',
        cols:'1'
    },
    {
        img:img9,
        title:'36',
        cols:'2'
    },
];
export default ImageData;
    
